doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                dbname:           sitebuilder
                user:             root
                password:         '%env(resolve:DATABASE_PASS)%'
                host:             '%env(resolve:DB_HOST)%'
                server_version:   '8.0.21'
                mapping_types:
                    enum: string
        types:
            login_type_enum: App\Enum\LoginTypeEnumType
            menu_item_type_enum: App\Enum\Plugin\Menu\MenuItemTypeEnumType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
