jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            serialize_null: false
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
