security:
    encoders:
        App\Entity\Authorization\User:
            algorithm: 'auto'

    providers:
        users:
            entity:
                class: 'App\Entity\Authorization\User'
                property: 'email'
    firewalls:
        login:
            pattern: ^/token
            stateless: true
            anonymous: true
            json_login:
                check_path: /token/create
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true

    access_control:
         - { path: ^/api, roles: ROLE_USER }
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
