security:
    encoders:
        App\Entity\User:
            algorithm: 'auto'

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'email'
    firewalls:
        login:
            pattern: ^/login/token
            stateless: true
            anonymous: true
            json_login:
                check_path: /login/token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email

        register:
            pattern: ^/login/registration
            stateless: true
            anonymous: true

        public:
            pattern: ^/page/(get-preview|get-public)
            stateless: true
            anonymous: true

        public_plugin_endpoint:
            pattern: ^/plugin/(plugin-form/save-data)
            stateless: true
            anonymous: true

        api:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: ^/login/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login/activation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/page/get-preview, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/page/get-public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/plugin/plugin-form/save-data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }
