controllers:
    resource: ../../src/Controller/
    type: annotation
    options:
        expose: true

kernel:
    resource: ../../src/Kernel.php
    type: annotation

security:
    resource: ../../src/Controller/Security
    type: annotation
    prefix: /security
    options:
        expose: true
