controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

frontend_components:
    resource: ../../src/Controller/FrontendComponents
    type: annotation
    prefix: /frontend-components
    options:
        expose: true

security:
    resource: ../../src/Controller/Security
    type: annotation
    prefix: /security
    options:
        expose: true
