version: '3'
services:
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password

  backend-nginx:
    image: nginx
    
  php-fpm-8.2:
    build: images/php-fpm-8.2

  redis:
    image: redis:latest
