version: '3'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=ag58#grg1@G8hR5
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.3
    volumes:
      - ./db-volume:/var/lib/mysql
      - ./config/mysql/dev:/etc/mysql/conf.d

  backend-nginx:
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.4
    volumes:
      - ../backend/sitebuilder:/var/www/backend
      - ../frontend:/var/www/frontend
      - ./config/nginx/backend-dev-local/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/backend-dev-local/sites-available:/etc/nginx/sites-available
      - ./config/nginx/backend-dev-local/conf.d:/etc/nginx/conf.d

  php-fpm-8.0:
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.7
    volumes:
      - ../backend/sitebuilder:/var/www/backend
    environment:
      - NODE_ENV=dev-local

  redis:
    image: redis:latest
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.8
    ports:
      - 6379:6379

networks:
  docker_network_sitebuilder:
    ipam:
      config:
        - subnet: 10.3.0.0/24
