version: '3'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=ag58#grg1@G8hR5
    networks:
      webnet:
        ipv4_address: 10.19.0.3
    volumes:
      - sitebuilder_dev_sql-volume:/var/lib/mysql
      - config/mysql/dev:/etc/mysql/conf.d

  backend:
    ports:
      - "8000:80"
    networks:
      webnet:
        ipv4_address: 10.19.0.4
    volumes:
      - ../backend:/var/www/public
      - config/nginx/backend-dev/nginx.conf:/etc/nginx/nginx.conf
      - config/nginx/backend-dev/sites-available:/etc/nginx/sites-available
      - config/nginx/backend-dev/conf.d:etc/nginx/conf.d

  adminer:
    image: adminer:latest
    networks:
      webnet:
        ipv4_address: 10.19.0.5
    ports:
      - 8080:8080

networks:
  webnet:
    ipam:
      config:
        - subnet: 10.19.0.0/24

volumes:
  sitebuilder_dev_sql-volume:
