version: '3'
services:
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=ag58#grg1@G8hR5
    networks:
      webnet:
        ipv4_address: 10.22.0.3
    volumes:
      - sitebuilder_sql-volume:/var/lib/mysql
      - config/mysql:/etc/mysql/conf.d

  backend:
    image: nginx:1.19.3
    ports:
      - "80:80"
    networks:
      webnet:
        ipv4_address: 10.22.0.4
    volumes:
      - ../backend:/var/www/public
      - config/nginx/backend/nginx.conf:/etc/nginx/nginx.conf
      - config/nginx/backend/sites-available:/etc/nginx/sites-available
      - config/nginx/backend/conf.d:etc/nginx/conf.d

  adminer:
    image: adminer:latest
    networks:
      webnet:
        ipv4_address: 10.22.0.5
    ports:
      - 8080:8080

networks:
  webnet:
    ipam:
      config:
        - subnet: 10.22.0.0/24

volumes:
  sitebuilder_sql-volume:
