<?php


namespace App\Security\Validator;


use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraint;

class UniqueEntityWithUserValidator extends UniqueEntityValidator
{
    public function __construct(ManagerRegistry $registry, public Security $security)
    {
        parent::__construct($registry);
    }

    public function validate($entity, Constraint $constraint)
    {
        $originUser = $entity->getUser();
        if(!$originUser) {
            $entity->setUser($this->security->getUser());
        }
        try {
            parent::validate($entity, $constraint); // TODO: Change the autogenerated stub
        } finally {
            $entity->setUser($originUser);
        }
    }
}
