version: '3'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=ag58#grg1@G8hR5
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.3
    volumes:
      - ./db-volume:/var/lib/mysql
      - ./config/mysql/dev:/etc/mysql/conf.d

  backend-nginx:
    ports:
      - "8000:80"
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.4
    volumes:
      - ../sitebuilder:/var/www
      - ./config/nginx/backend-dev-local/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/backend-dev-local/sites-available:/etc/nginx/sites-available
      - ./config/nginx/backend-dev-local/conf.d:/etc/nginx/conf.d

  php-fpm:
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.6
    volumes:
      - ../sitebuilder:/var/www
    environment:
      - NODE_ENV=dev-local

  php-fpm-8.0:
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.7
    volumes:
      - ../sitebuilder:/var/www
    environment:
      - NODE_ENV=dev-local

  adminer:
    image: adminer:latest
    networks:
      docker_network_sitebuilder:
        ipv4_address: 10.3.0.5
    ports:
      - 8080:8080

networks:
  docker_network_sitebuilder:
    ipam:
      config:
        - subnet: 10.3.0.0/24
